name: Run Rust Clippy

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo clippy
        run: cargo clippy
